FROM debian:latest
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y git make curl
RUN apt-get install -y bc bzip2 libbz2-dev gcc libncurses-dev openjdk-11-jdk-headless unzip xz-utils zlib1g-dev liblzma-dev
RUN apt-get install -y python-dev python-pip python3-pip ncbi-blast+ libidn11 bwa bowtie2 libtbb-dev
RUN apt-get install -y python3-dev python3-pip python3-setuptools

RUN #easy_install-3.6 pip
RUN pip2 install biopython
RUN pip3 install pyfastaq

RUN curl -fsSL 'https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.7.1/ncbi-blast-2.7.1+-x64-linux.tar.gz' | tar -xz -C /usr/local/bin
RUN find /usr/local/bin/ncbi-blast*/bin -maxdepth 1 -executable -type f -exec ln -s {} /usr/local/bin \;
RUN curl -fsSL 'https://mafft.cbrc.jp/alignment/software/mafft-7.407-without-extensions-src.tgz' | tar -xz -C /tmp/
WORKDIR /tmp/mafft-7.407-without-extensions/core
RUN make
RUN make install

RUN curl -fsSL 'https://downloads.sourceforge.net/project/smalt/smalt-0.7.6-static.tar.gz' | tar -xz -C /tmp/
WORKDIR /tmp/smalt-0.7.6
RUN ./configure
RUN make
RUN make install

RUN curl -fsSL 'https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2' | tar -xj -C /tmp/
WORKDIR /tmp/samtools-1.9
RUN ./configure
RUN make
RUN make install

RUN curl -fsSL 'http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/Trimmomatic-0.38.zip' -o /usr/local/bin/Trimmomatic-0.38.zip
WORKDIR /usr/local/bin
RUN unzip Trimmomatic-0.38.zip
RUN  ln -s /usr/local/bin/Trimmomatic-0.38/trimmomatic-0.38.jar /usr/local/bin
RUN curl -fsSL https://raw.githubusercontent.com/connor-lab/singularity-recipes/master/scripts/trimmomatic -o /usr/local/bin/trimmomatic
RUN chmod 775 /usr/local/bin/trimmomatic
RUN git clone https://github.com/lh3/seqtk.git /tmp/seqtk
WORKDIR /tmp/seqtk
RUN make
RUN cp /tmp/seqtk/seqtk /usr/local/bin
RUN rm -rf /tmp/seqtk
RUN git clone https://github.com/ChrisHIV/shiver/ /usr/local/bin/shiver

RUN #cd /usr/local/bin/shiver
RUN #git reset --hard ce3fc9fc05d2f4cef9e5e8ae6ec3f91e490b5165R
RUN #curl -fsSL 'https://github.com/ChrisHIV/shiver/archive/v1.3.5.tar.gz' | tar -xz -C /usr/local/bin && mv /usr/local/bin/shiver-1.3.5 /usr/local/bin/shiver
RUN #find /usr/local/bin/shiver -maxdepth 1 -executable -type f -exec cp {} /usr/local/bin \;
RUN #sed -e '/^ThisDir/ s/^#*/#/' -i /usr/local/bin/shiver_*.sh
RUN #sed -i '/^ToolsDir/i ThisDir="/usr/local/bin/shiver"' /usr/local/bin/shiver_*.sh
RUN rm -rf /tmp/seqtk /tmp/samtools* /tmp/smalt* /tmp/mafft*

ENV LC_ALL=C
ENV export LC_ALL
ENV PATH=$PATH:/usr/local/bin/shiver
ENV export PATH

ENTRYPOINT exec shiver_init.sh "$@"