FROM debian:latest

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y git make
RUN apt-get install -y curl bash gcc bzip2 libc6 zlib1g-dev openjdk-11-jre libncurses-dev libghc-bzlib-dev liblzma-dev
RUN apt-get install -y python2

RUN curl -fsSL 'https://github.com/dkoboldt/varscan/releases/download/2.4.2/VarScan.v2.4.2.jar' -o /usr/local/bin/varscan.jar

RUN curl -fsSL 'https://github.com/samtools/samtools/archive/1.1.tar.gz' | tar -xz -C /tmp/
RUN curl -fsSL 'https://github.com/samtools/htslib/archive/1.1.tar.gz' | tar -xz -C /tmp && mv /tmp/htslib-1.1 /tmp/htslib
WORKDIR /tmp/htslib
RUN make
WORKDIR /tmp/samtools-1.1
RUN make

RUN curl -fsSL 'https://github.com/CSB5/lofreq/blob/master/dist/lofreq_star-2.1.3.1.tar.gz?raw=true' | tar -xz -C /tmp
WORKDIR /tmp/lofreq_star-2.1.3.1
RUN ./configure SAMTOOLS=/tmp/samtools-1.1 HTSLIB=/tmp/htslib && make install

RUN curl -fsSL 'https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2' | tar -xj -C /tmp/
WORKDIR /tmp/samtools-1.9
RUN ./configure && make && make install

RUN curl -fsSL 'https://github.com/samtools/bcftools/releases/download/1.9/bcftools-1.9.tar.bz2' | tar -xj -C /tmp/
WORKDIR /tmp/bcftools-1.9
RUN ./configure && make && make install

RUN curl -fsSL 'https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2' | tar -xj -C /tmp/
WORKDIR /tmp/htslib-1.9

RUN ./configure && make && make install
RUN rm -rf /tmp/samtools* /tmp/lofreq* /tmp/htslib* /tmp/bcftools*