FROM debian:latest

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install git make
RUN apt-get -y install bash bzip2 curl gcc g++ libc6-dev libncurses-dev xz-utils zlib1g-dev
RUN apt-get -y install python3 python3-dev python3-pip
RUN apt-get -y install libfreetype6 libpng-dev

WORKDIR /usr/local/bin
RUN curl -fsSL "https://github.com/jgm/pandoc/releases/download/2.3/pandoc-2.3-linux.tar.gz" | tar xz
RUN find /usr/local/bin/pandoc-2.3 -name "pandoc" -exec ln -s {} /usr/local/bin \;

RUN python3 -m pip install git+https://github.com/ewels/MultiQC.git




