FROM debian:latest

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install git make
RUN apt-get -y install bash bzip2 g++ gcc libc6-dev libncurses-dev openjdk-11-jdk perl wget xz-utils libghc-bzlib-dev unzip zlib1g-dev liblzma-dev

RUN git clone https://github.com/lh3/minimap2 /tmp/minimap2
WORKDIR /tmp/minimap2
RUN make
RUN mv /tmp/minimap2/minimap2 /usr/local/bin/
RUN rm -rf /tmp/minimap2

RUN wget https://github.com/samtools/samtools/releases/download/1.8/samtools-1.8.tar.bz2 -O /tmp/samtools.tar.bz2
WORKDIR /tmp
RUN tar xvjf samtools.tar.bz2
WORKDIR samtools-1.8
RUN ./configure && make && make install

RUN wget https://github.com/broadinstitute/picard/releases/download/2.18.14/picard.jar -O /usr/local/bin/picard.jar

RUN wget https://raw.githubusercontent.com/connor-lab/singularity-recipes/master/scripts/picard -O /usr/local/bin/picard
RUN chmod 775 /usr/local/bin/picard
